import { notFound } from "next/navigation";
import { getPortalProject } from "~/services/finance";
import { getPortalFeedback } from "~/services/portal-feedback";
import PortalCollaboration from "./portal-collaboration";

export default async function ClientPortalPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params; const project = await getPortalProject(token); if (!project) notFound();
  const feedback = await getPortalFeedback(token); const completed = project.tasks.filter((task) => task.status === "completed").length;
  return <main className="min-h-screen bg-[#f7f7f6] px-5 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><header className="rounded-3xl bg-[#171717] p-7 text-white shadow-xl sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-red-300">WorkNest client portal</p><h1 className="mt-2 text-3xl font-bold">{project.name}</h1><p className="mt-2 max-w-2xl text-neutral-300">{project.description}</p><div className="mt-5 flex flex-wrap gap-3 text-sm text-neutral-400"><span>Target date: {new Date(project.deadline).toLocaleDateString()}</span><span className="text-neutral-700">•</span><span>{project.client.name}</span></div></header><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-neutral-200 bg-white p-5"><h2 className="font-bold text-neutral-900">Project progress</h2><p className="mt-1 text-sm text-neutral-500">{completed} of {project.tasks.length} tasks complete</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-neutral-200"><div className="h-full bg-[#d92d27]" style={{ width: `${project.tasks.length ? (completed / project.tasks.length) * 100 : 0}%` }}/></div><div className="mt-5 space-y-2">{project.tasks.map((task) => <div key={task.id} className="flex justify-between rounded-xl bg-neutral-50 px-3 py-2.5 text-sm"><span>{task.title}</span><span className="capitalize text-neutral-500">{task.status.replace("_", " ")}</span></div>)}</div></section><section className="rounded-2xl border border-neutral-200 bg-white p-5"><h2 className="font-bold text-neutral-900">Invoices</h2><div className="mt-4 space-y-2">{project.invoices.length ? project.invoices.map((invoice) => <div key={invoice.id} className="flex justify-between rounded-xl bg-neutral-50 px-3 py-2.5 text-sm"><span><b>{invoice.number}</b> · <span className="capitalize text-neutral-500">{invoice.status}</span></span><span className="font-semibold">{invoice.total.toFixed(2)}</span></div>) : <p className="text-sm text-neutral-500">No invoices have been issued.</p>}</div></section></div><div className="mt-6"><PortalCollaboration token={token} feedback={feedback.map((item) => ({ ...item, createdAt: item.createdAt.toISOString() }))} /></div><p className="mt-8 text-center text-xs text-neutral-400">Secure shared project view powered by WorkNest</p></div></main>;
}
