"use client";

import { useState } from "react";

type Feedback = { id: string; type: "message" | "approval"; message: string; createdAt: string };
export default function PortalCollaboration({ token, feedback }: { token: string; feedback: Feedback[] }) {
  const [message, setMessage] = useState(""); const [items, setItems] = useState(feedback); const [status, setStatus] = useState(""); const [pending, setPending] = useState(false);
  async function send(type: "message" | "approval") { const text = type === "approval" ? "Approved by client" : message.trim(); if (!text || pending) return; setPending(true); setStatus(""); try { const response = await fetch(`/api/portal/${token}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type, message: text }) }); const data = await response.json() as { error?: string }; if (!response.ok) { setStatus(data.error ?? "Could not send feedback."); return; } setItems((current) => [{ id: crypto.randomUUID(), type, message: text, createdAt: new Date().toISOString() }, ...current]); setMessage(""); setStatus(type === "approval" ? "Approval recorded." : "Message sent to your project team."); } catch { setStatus("Could not connect right now."); } finally { setPending(false); } }
  return <section className="rounded-2xl border border-neutral-200 bg-white p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#d92d27]">Work together</p><h2 className="mt-1 font-bold text-neutral-900">Feedback & approvals</h2><p className="mt-1 text-sm text-neutral-500">Send a note to the project team or approve the current delivery.</p></div><button type="button" onClick={() => void send("approval")} disabled={pending} className="shrink-0 rounded-xl bg-[#d92d27] px-3 py-2 text-xs font-bold text-white shadow-lg shadow-red-100 disabled:opacity-50">Approve project</button></div><textarea value={message} onChange={(event) => setMessage(event.target.value)} maxLength={1200} placeholder="Leave feedback for the project team…" className="mt-4 min-h-24 w-full rounded-xl border border-neutral-200 bg-neutral-50 px-3 py-2.5 text-sm" /><div className="mt-2 flex items-center justify-between"><span className="text-xs text-neutral-400">{status || "Your message is shared securely with the team."}</span><button type="button" onClick={() => void send("message")} disabled={pending || !message.trim()} className="rounded-xl border border-neutral-200 bg-white px-3 py-2 text-xs font-bold text-neutral-700 disabled:opacity-50">{pending ? "Sending…" : "Send feedback"}</button></div>{items.length > 0 && <div className="mt-5 space-y-2 border-t border-neutral-100 pt-4">{items.slice(0, 5).map((item) => <div key={item.id} className="rounded-xl bg-neutral-50 p-3"><div className="flex items-center justify-between"><span className={`text-[10px] font-bold uppercase tracking-wide ${item.type === "approval" ? "text-emerald-700" : "text-neutral-500"}`}>{item.type === "approval" ? "Approved" : "Feedback"}</span><time className="text-[10px] text-neutral-400">{new Date(item.createdAt).toLocaleString()}</time></div><p className="mt-1 text-sm text-neutral-700">{item.message}</p></div>)}</div>}</section>;
}
