import "server-only";
import connectDB from "~/lib/db";
import JoinRequest from "~/models/join_request";
import Organization from "~/models/organization";
import UserOrganization from "~/models/user_organization";

export type JoinRequestSummary = { id: string; userId: string; userName: string; userEmail: string; organizationId: string; organizationName: string; message: string; status: string; createdAt: Date };

type RequestDocument = { _id: { toString(): string }; user?: { _id?: { toString(): string }; name?: string; email?: string } | { toString(): string }; organization?: { _id?: { toString(): string }; name?: string } | { toString(): string }; message?: string; status: string; createdAt: Date };
function mapRequest(request: RequestDocument): JoinRequestSummary { const person = typeof request.user === "object" && request.user && "name" in request.user ? request.user : undefined; const organization = typeof request.organization === "object" && request.organization && "name" in request.organization ? request.organization : undefined; return { id: request._id.toString(), userId: typeof request.user === "object" && request.user && "_id" in request.user && request.user._id ? request.user._id.toString() : String(request.user), userName: person?.name ?? "Unknown user", userEmail: person?.email ?? "", organizationId: typeof request.organization === "object" && request.organization && "_id" in request.organization && request.organization._id ? request.organization._id.toString() : String(request.organization), organizationName: organization?.name ?? "Organization", message: request.message ?? "", status: request.status, createdAt: request.createdAt }; }

export async function findOrganizationByName(name: string) { await connectDB(); return Organization.findOne({ name: { $regex: name.trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), $options: "i" }, joinRequestsEnabled: { $ne: false } }).select("_id name").lean(); }
export async function getUserJoinRequests(userId: string) { await connectDB(); return (await JoinRequest.find({ user: userId }).populate("organization", "name").sort({ createdAt: -1 }).limit(20).lean()).map(mapRequest); }
export async function createJoinRequest(userId: string, organizationId: string, message: string) { await connectDB(); const existing = await UserOrganization.exists({ user: userId, organization: organizationId }); if (existing) return { ok: false as const, error: "You already belong to this organization." }; const pending = await JoinRequest.exists({ user: userId, organization: organizationId, status: "pending" }); if (pending) return { ok: false as const, error: "You already have a pending request there." }; const request = await JoinRequest.create({ user: userId, organization: organizationId, message: message.trim() }); return { ok: true as const, id: request._id.toString() }; }
export async function getOrganizationJoinRequests(organizationId: string) { await connectDB(); return (await JoinRequest.find({ organization: organizationId, status: "pending" }).populate("user", "name email avatar").populate("organization", "name").sort({ createdAt: 1 }).lean()).map(mapRequest); }
export async function reviewJoinRequest(requestId: string, organizationId: string, reviewerId: string, decision: "approved" | "rejected") { await connectDB(); const request = await JoinRequest.findOne({ _id: requestId, organization: organizationId, status: "pending" }); if (!request) return { ok: false as const, error: "Request not found or already reviewed." }; if (decision === "approved") { const already = await UserOrganization.exists({ user: request.user, organization: organizationId }); if (!already) await UserOrganization.create({ user: request.user, organization: organizationId, role: "member" }); } request.status = decision; request.reviewedBy = reviewerId; request.reviewedAt = new Date(); await request.save(); return { ok: true as const, userId: request.user.toString() }; }
