"use client";
import { useActionState } from "react";
import { createTaskTemplateAction, type PlanningActionState } from "~/actions/planning";
import { PRIORITY } from "~/lib/constants/roles";
const initial: PlanningActionState = {};

export function TemplateCreator({ projectId }: { projectId: string }) {
  const [state, action, pending] = useActionState(createTaskTemplateAction, initial);
  return <details className="rounded-2xl border border-neutral-200 bg-white"><summary className="cursor-pointer px-5 py-4 text-sm font-semibold text-neutral-800">Create a reusable task template</summary><form action={action} className="grid gap-3 border-t border-neutral-100 p-5 sm:grid-cols-2"><input type="hidden" name="projectId" value={projectId}/><input required name="name" maxLength={80} placeholder="Template name" className="rounded-xl border border-neutral-200 px-3 py-2 text-sm"/><input required name="title" maxLength={200} placeholder="Default task title" className="rounded-xl border border-neutral-200 px-3 py-2 text-sm"/><textarea name="description" placeholder="Default description" className="sm:col-span-2 rounded-xl border border-neutral-200 px-3 py-2 text-sm"/><select name="priority" defaultValue="medium" className="rounded-xl border border-neutral-200 bg-white px-3 py-2 text-sm">{PRIORITY.map((priority) => <option key={priority} value={priority}>{priority}</option>)}</select><select name="recurrence" defaultValue="none" className="rounded-xl border border-neutral-200 bg-white px-3 py-2 text-sm"><option value="none">Does not repeat</option><option value="daily">Every day</option><option value="weekly">Every week</option><option value="monthly">Every month</option></select><input name="estimatedHours" type="number" min="0" step="0.5" placeholder="Estimated hours (optional)" className="rounded-xl border border-neutral-200 px-3 py-2 text-sm"/><button disabled={pending} className="rounded-xl bg-neutral-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Saving…" : "Save template"}</button>{state.error && <p className="sm:col-span-2 text-sm text-red-600">{state.error}</p>}{state.success && <p className="sm:col-span-2 text-sm text-emerald-600">Template saved.</p>}</form></details>;
}
