import Link from "next/link";
import JoinRequestForm from "./join-request-form";
import { getCurrentUser } from "~/lib/auth/current-user";
import { getUserJoinRequests } from "~/services/join-request";

export default async function JoinOrganizationPage() {
  const user = await getCurrentUser(); const requests = user ? await getUserJoinRequests(user.id) : [];
  return <div className="w-full max-w-xl"><Link href="/onboarding" className="text-sm font-semibold text-neutral-500 hover:text-neutral-900">← Back to choices</Link><div className="mt-5 rounded-3xl border border-neutral-200 bg-white p-7 shadow-sm sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#d92d27]">Join an organization</p><h1 className="mt-2 text-2xl font-bold text-neutral-950">Connect to your team</h1><p className="mt-2 text-sm leading-6 text-neutral-600">The safest way to join is through an invitation or an approval-based request. Your role and project access are assigned only after approval.</p><div className="mt-6 space-y-3"><div className="rounded-2xl bg-neutral-50 p-4"><p className="font-bold text-neutral-800">Already received an invitation?</p><p className="mt-1 text-sm text-neutral-500">Open the invitation link from your email. WorkNest will verify it and add the organization to your workspace.</p></div><JoinRequestForm /></div>{requests.length > 0 && <div className="mt-6"><p className="text-xs font-bold uppercase tracking-wide text-neutral-500">Your requests</p><div className="mt-2 space-y-2">{requests.map((request) => <div key={request.id} className="flex items-center justify-between rounded-xl border border-neutral-100 px-3 py-2.5"><span className="text-sm font-semibold text-neutral-700">{request.organizationName}</span><span className="rounded-full bg-neutral-100 px-2 py-1 text-[10px] font-bold uppercase text-neutral-500">{request.status}</span></div>)}</div></div>}<div className="mt-7 flex flex-wrap gap-3"><Link href="/onboarding/personal" className="rounded-xl border border-neutral-200 px-4 py-2.5 text-sm font-semibold text-neutral-700 hover:bg-neutral-50">Continue personally</Link><Link href="/onboarding/create" className="rounded-xl bg-[#d92d27] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#b42318]">Create instead</Link></div></div></div>;
}
