"use server";
import { revalidatePath } from "next/cache";
import { requireOrgContext } from "~/lib/auth/current-org";
import { can, PERMISSION_DENIED_MESSAGE } from "~/lib/permissions/permissions";
import { createInvoice, updateProjectFinance } from "~/services/finance";
import { getProjectForOrg } from "~/services/project";
import { logActivity } from "~/services/activity";
export interface FinanceActionState { error?: string; success?: boolean; }
export async function saveProjectFinance(_state: FinanceActionState, formData: FormData): Promise<FinanceActionState> { const { organization, role } = await requireOrgContext(); if (!can(role, "projects:update")) return { error: PERMISSION_DENIED_MESSAGE }; const projectId = formData.get("projectId"), budget = Number(formData.get("budget")), hourlyRate = Number(formData.get("hourlyRate")), portalEnabled = formData.get("portalEnabled") === "true"; if (typeof projectId !== "string" || !Number.isFinite(budget) || budget < 0 || !Number.isFinite(hourlyRate) || hourlyRate < 0) return { error: "Enter valid non-negative amounts." }; if (!(await updateProjectFinance(projectId, organization.id, budget, hourlyRate, portalEnabled))) return { error: "Project not found." }; revalidatePath(`/dashboard/projects/${projectId}`); return { success: true }; }
export async function createInvoiceAction(_state: FinanceActionState, formData: FormData): Promise<FinanceActionState> { const { organization, role, user } = await requireOrgContext(); if (!can(role, "projects:update")) return { error: PERMISSION_DENIED_MESSAGE }; const projectId = formData.get("projectId"), description = formData.get("description"), quantity = Number(formData.get("quantity")), unitPrice = Number(formData.get("unitPrice")), dueDate = formData.get("dueDate"); if (typeof projectId !== "string" || typeof description !== "string" || !description.trim() || !Number.isFinite(quantity) || quantity <= 0 || !Number.isFinite(unitPrice) || unitPrice < 0 || typeof dueDate !== "string" || Number.isNaN(Date.parse(dueDate))) return { error: "Complete the invoice details." }; const project = await getProjectForOrg(projectId, organization.id); if (!project) return { error: "Project not found." }; if (!(await createInvoice({ projectId, organizationId: organization.id, clientId: project.client.id, description: description.trim(), quantity, unitPrice, dueDate: new Date(dueDate) }))) return { error: "Could not create invoice." }; await logActivity({ organizationId: organization.id, userId: user.id, action: "updated", entityType: "Project", entityId: projectId, metadata: { event: "invoice_created", description: description.trim(), total: quantity * unitPrice } }); revalidatePath(`/dashboard/projects/${projectId}`); return { success: true }; }
