"use client";

import { useActionState } from "react";
import { createMilestoneAction, toggleMilestoneAction, type PlanningActionState } from "~/actions/planning";
import type { MilestoneSummary } from "~/services/milestone";
const initial: PlanningActionState = {};

export default function Milestones({ projectId, milestones, canManage }: { projectId: string; milestones: MilestoneSummary[]; canManage: boolean }) {
  const [state, action, pending] = useActionState(createMilestoneAction, initial);
  return <div className="worknest-panel rounded-2xl border border-neutral-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#d92d27]">Project plan</p><h2 className="mt-1 font-bold text-neutral-900">Milestones</h2></div><span className="text-sm text-neutral-400">{milestones.filter((item) => item.completed).length}/{milestones.length}</span></div><div className="mt-4 space-y-2">{milestones.length === 0 ? <p className="rounded-xl bg-neutral-50 px-4 py-3 text-sm text-neutral-500">Set a milestone to give the team a clear target.</p> : milestones.map((milestone) => <div key={milestone.id} className="flex items-center gap-3 rounded-xl border border-neutral-100 px-3 py-2.5"><form action={toggleMilestoneAction}><input type="hidden" name="milestoneId" value={milestone.id}/><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="completed" value={String(!milestone.completed)}/><button disabled={!canManage} aria-label={`Mark ${milestone.title} ${milestone.completed ? "incomplete" : "complete"}`} className={`grid h-5 w-5 place-items-center rounded-full border text-xs ${milestone.completed ? "border-emerald-600 bg-emerald-600 text-white" : "border-neutral-300"}`}>{milestone.completed ? "✓" : ""}</button></form><span className={`min-w-0 flex-1 text-sm font-medium ${milestone.completed ? "text-neutral-400 line-through" : "text-neutral-800"}`}>{milestone.title}</span><time className="text-xs text-neutral-500">{new Date(milestone.dueDate).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}</time></div>)}</div>{canManage && <form action={action} className="mt-4 grid gap-2 sm:grid-cols-[1fr_150px_auto]"><input type="hidden" name="projectId" value={projectId}/><input required name="title" maxLength={200} placeholder="e.g. Design approved" className="rounded-xl border border-neutral-200 px-3 py-2 text-sm"/><input required name="dueDate" type="date" className="rounded-xl border border-neutral-200 px-3 py-2 text-sm"/><button disabled={pending} className="rounded-xl bg-neutral-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Add</button>{state.error && <p className="text-sm text-red-600 sm:col-span-3">{state.error}</p>}</form>}</div>;
}
